Models/FoodCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FoodHub.Models
{
    public class FoodCategory
    {
        public int Id { get; set; }
        [Display(Name = "Category Name")]
        [Required(ErrorMessage = "The category name cannot be blank")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a category name between 3 and 50 characters in length")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$", ErrorMessage = "Please enter a category name beginning with a capital letter and made up of letters and spaces only")]
        public string Name { get; set; }
        public string Description { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
       // public virtual ICollection<Vendor> Vendors { get; set; }
    }
}

ViewModels/FoodCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodHub.ViewModels
{
    public class FoodCategoryViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The category name cannot be blank")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a category name between 3 and 50 characters in length")]
        [RegularExpression(@"^[a-zA-Z0-9'-'\s]*$", ErrorMessage = "Please enter a product name made up of letters and numbers only")]
        public string Name { get; set; }

        [RegularExpression(@"^[,;a-zA-Z0-9'-'\s]*$", ErrorMessage = "Please enter a productdescription made up of letters and numbers only")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public int FoodCategoryId { get; set; }

       // public SelectList FoodCategoryList { get; set; }

        public List<SelectList> ImageLists { get; set; }

        public string[] FoodCategoryImages { get; set; }


    }
}

Controllers/FoodCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodHub.DAL;
using FoodHub.Models;
using FoodHub.ViewModels;

namespace FoodHub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FoodCategoriesController : Controller
    {
        private FoodContext db = new FoodContext();

        // GET: FoodCategories
        [AllowAnonymous]
        public ActionResult Index() => View(db.FoodCategories.OrderBy(c => c.Name).ToList());
        

        // GET: FoodCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodCategory foodCategory = db.FoodCategories.Find(id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // GET: FoodCategories/Create
        public ActionResult Create()
        {
            FoodCategoryViewModel viewModel = new FoodCategoryViewModel();
            viewModel.ImageLists = new List<SelectList>();
            //viewModel.FoodCategoryList = new SelectList(db.FoodCategories, "Id", "Name");
            for (int i = 0; i < Constants.NumberOfFoodImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.FoodCategoryImages, "id", "FileName"));
            }
            return View();
        }

        // POST: FoodCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] FoodCategory foodCategory)
        {
            if (ModelState.IsValid)
            {
                db.FoodCategories.Add(foodCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodCategory);
        }

        // GET: FoodCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodCategory foodCategory = db.FoodCategories.Find(id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // POST: FoodCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] FoodCategory foodCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(foodCategory);
        }

        // GET: FoodCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodCategory foodCategory = db.FoodCategories.Find(id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // POST: FoodCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FoodCategory foodCategory = db.FoodCategories.Find(id);
            db.FoodCategories.Remove(foodCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FoodHub.DAL;
using FoodHub.Models;
using FoodHub.ViewModels;
using PagedList;

namespace FoodHub.Controllers
{
    [Authorize(Roles ="Admin")]
    public class FoodsController : Controller
    {
        private FoodContext db = new FoodContext();

        // GET: Foods
        [AllowAnonymous]
        public ActionResult Index(string category, string vendor, string search, string sortBy, int? page)
        {

            //instantiate a new view Model
            FoodIndexViewModel viewModel = new FoodIndexViewModel();

            var foods = db.Foods.Include(f => f.FoodCategory).Include(f => f.Vendor);
            if (!String.IsNullOrEmpty(category))
            {
                foods = foods.Where(p => p.FoodCategory.Name == category);
               
            }

            if (!String.IsNullOrEmpty(vendor))
            {
                foods = foods.Where(v => v.Vendor.Name == vendor);

            }

            if (!String.IsNullOrEmpty(search))
            {
                foods = foods.Where(f => f.Name.Contains(search) ||
                f.Description.Contains(search) ||
                f.FoodCategory.Name.Contains(search));
                viewModel.Search = search;
            }

            //group search results into categories and count how many items in each category
            viewModel.CatsWithCount = from matchingFoods in foods
                                      where
                                      matchingFoods.FoodCategoryId != null
                                      group matchingFoods by
                                      matchingFoods.FoodCategory.Name into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          FoodCategoryName = catGroup.Key,
                                          FoodCount = catGroup.Count()
                                      };

            //group search results into vendors and count how many items in each vendor
            viewModel.VendWithCount = from matchingVendors in foods
                                      where
                                      matchingVendors.VendorId != null
                                      group matchingVendors by
                                      matchingVendors.Vendor.Name into
                                      vendGroup
                                      select new VendorWithCount()
                                      {
                                          VendorName = vendGroup.Key,
                                          FoodCount = vendGroup.Count()
                                      };

            // var categories = foods.OrderBy(f => f.FoodCategory.Name).Select(f => 
            //f.FoodCategory.Name).Distinct();

            if (!String.IsNullOrEmpty(category))
            {
                foods = foods.Where(p => p.FoodCategory.Name == category);
                viewModel.FoodCategory = category;
            }

            var vendors = foods.OrderBy(v => v.Vendor.Name).Select(v => 
            v.Vendor.Name).Distinct();

            if (!String.IsNullOrEmpty(vendor))
            {
                foods = foods.Where(p => p.Vendor.Name == vendor);
                viewModel.Vendor = vendor;
            }

            //sort the results
            switch (sortBy)
            {
                case "price_lowest":
                    foods = foods.OrderBy(p => p.Price);
                    break;
                case "price_highest":
                   foods = foods.OrderByDescending(p => p.Price);
                    break;
                default:
                    foods = foods.OrderBy(p => p.Name);
                    break;
            }

            //ViewBag.FoodCategory = new SelectList(categories);
            // viewModel.Foods = foods;
            // ViewBag.Vendor = new SelectList(vendors);

           
            int currentPage = (page ?? 1);
            viewModel.Foods = foods.ToPagedList(currentPage, Constants.PageItems);
            viewModel.SortBy = sortBy;
            viewModel.Sorts = new Dictionary<string, string>
            {
                {"Price low to high", "price_lowest" },
                {"Price high to low", "price_highest" }
            };


            return View(viewModel);
        }

        // GET: Foods/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // GET: Foods/Create

            public ActionResult Create()
            {
                FoodViewModel viewModel = new FoodViewModel();
                viewModel.FoodCategoryList = new SelectList(db.FoodCategories, "Id", "Name");
                viewModel.VendorList = new SelectList(db.Vendors, "Id", "Name");
                viewModel.ImageLists = new List<SelectList>();
                for (int i = 0; i < Constants.NumberOfFoodImages; i++)
                {
                    viewModel.ImageLists.Add(new SelectList(db.FoodImages, "Id", "FileName"));
                }
                return View(viewModel);


                //ViewBag.FoodCategoryId = new SelectList(db.FoodCategories, "Id", "Name");
                //ViewBag.VendorId = new SelectList(db.Vendors, "Id", "Name");
                //return View();
            }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FoodViewModel viewModel)
        {
            Food food = new Food();
            food.Name = viewModel.Name;
            food.Description = viewModel.Description;
            food.Price = viewModel.Price;
            food.FoodCategoryId = viewModel.FoodCategoryId;
            food.VendorId = viewModel.VendorId;
            food.FoodImageMappings = new List<FoodImageMapping>();

            //get a list of selected images without any blanks
            string[] foodImages = viewModel.FoodImages.Where(pi =>
            !string.IsNullOrEmpty(pi)).ToArray();
            for (int i = 0; i < foodImages.Length; i++)
            {
                food.FoodImageMappings.Add(new FoodImageMapping
                {
                    FoodImage = db.FoodImages.Find(int.Parse(foodImages[i])),
                    ImageNumber = i
                });
            }
            if (ModelState.IsValid)
            {
                db.Foods.Add(food);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            viewModel.FoodCategoryList = new SelectList(db.FoodCategories, "Id", "Name", food.FoodCategoryId);
            viewModel.VendorList = new SelectList(db.Vendors, "Id", "Name", food.VendorId);
            viewModel.ImageLists = new List<SelectList>();
            for (int i = 0; i < Constants.NumberOfFoodImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.FoodImages, "ID", "FileName",
                viewModel.FoodImages[i]));
            }
            return View(viewModel);
        }

        // GET: Foods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }

            FoodViewModel viewModel = new FoodViewModel();
            viewModel.FoodCategoryList = new SelectList(db.FoodCategories, "Id", "Name", food.FoodCategoryId);
            viewModel.VendorList = new SelectList(db.Vendors, "Id", "Name", food.VendorId);
            viewModel.ImageLists = new List<SelectList>();
            foreach (var imageMapping in food.FoodImageMappings.OrderBy(pim => pim.ImageNumber))
            {
                viewModel.ImageLists.Add(new SelectList(db.FoodImages, "Id", "FileName",
                imageMapping.FoodImageId));
            }
            for (int i = viewModel.ImageLists.Count; i < Constants.NumberOfFoodImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.FoodImages, "Id", "FileName"));
            }
            viewModel.Id = food.Id;
            viewModel.Name = food.Name;
            viewModel.Description = food.Description;
            viewModel.Price = food.Price;
            return View(viewModel);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price,FoodCategoryId,VendorId")] Food food)
        {
            if (ModelState.IsValid)
            {
                db.Entry(food).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FoodCategoryId = new SelectList(db.FoodCategories, "Id", "Name", food.FoodCategoryId);
            ViewBag.VendorId = new SelectList(db.Vendors, "Id", "Name", food.VendorId);
            return View(food);
        }

        // GET: Foods/Delete/5

Views/FoodCategories/Create.cshtml
@*@model FoodHub.Models.FoodCategory*@
@model FoodHub.ViewModels.FoodCategoryViewModel

@{
    ViewBag.Title = "Create Category";
}

<h2>@ViewBag.Title</h2>

<br/><br/>

@using (Html.BeginForm())
{
    <p class="alert-info"> All fields are <strong>required</strong>!</p>
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", autofocus="autofocus", placeholder="eg breakfast" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/FoodCategories/Delete.cshtml
@model FoodHub.Models.FoodCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/FoodCategories/Details.cshtml
@model FoodHub.Models.FoodCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FoodCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/FoodCategories/Edit.cshtml
@model FoodHub.Models.FoodCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FoodCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/FoodCategories/Index.cshtml
@model IEnumerable<FoodHub.Models.FoodCategory>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Title</h2>

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Index", "Foods", new { category = item.Name }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    @Html.Raw(" | ")
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
            </td>
        </tr>
    }

</table>